version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: currency_exchange_rate
        env_file:
            - .env
        ports:
            - "3000:3000"
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: postgres_db
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
